# Generated by Django 6.0 on 2025-12-18 21:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_game_customuser_losses_customuser_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'),
        ),
    ]
