# Generated by Django 6.0 on 2025-12-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_game_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
    ]
