# Generated by Django 6.0 on 2025-12-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_game_in_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='white_or_black',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
