# Generated by Django 6.0 on 2025-12-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_draws_customuser_white_or_black'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board',
        ),
        migrations.RemoveField(
            model_name='game',
            name='in_game',
        ),
        migrations.AddField(
            model_name='game',
            name='move_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
