# Generated by Django 6.0 on 2025-12-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_game_board_remove_game_in_game_game_move_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='white_turn',
            field=models.BooleanField(default=True),
        ),
    ]
