# Generated by Django 6.0 on 2025-12-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_game_white_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='latest_move',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='game',
            name='back_row_360',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='over',
            field=models.BooleanField(default=False),
        ),
    ]
