# Generated by Django 6.0 on 2025-12-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_active_customuser_latest_move_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='last_seen_move',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
