# Generated by Django 6.0 on 2025-12-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_game_in_game_game_last_seen_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='latest_move',
        ),
        migrations.AddField(
            model_name='game',
            name='latest_move',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
