# Generated by Django 6.0 on 2025-12-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_latest_move_game_latest_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='game',
        ),
    ]
