# Generated by Django 6.0 on 2025-12-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active',
        ),
    ]
