# Generated by Django 6.0 on 2025-12-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='white_or_black',
        ),
    ]
