# Generated by Django 6.0 on 2025-12-24 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_white_or_black'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='spec_opponent_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='game',
            name='waiting_for_specific_user',
            field=models.BooleanField(default=False),
        ),
    ]
