# Generated by Django 4.2.27 on 2026-01-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_friends_game_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rematch_black_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='rematch_new_game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rematch_white_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
